### ISSUE TITLE
Plots on top of each other with `position: absolute;`

### ISSUE THREAD

**Issue by kmarchais** [Kitware/trame-plotly#4]
Hello, I am a beginner with trame and I am facing an issue with a plotly figure.
When I want to put an element after a plotly figure (for example another plotly figure as shown below), one is hiding the other.
By removing `position: absolute;`, it works as I want.

```python
import plotly.graph_objects as go
from trame.widgets import plotly
from trame.app import get_server
from trame.ui.html import DivLayout

fig = go.Figure(
    data=go.Contour(
        z=[
            [10, 10.625, 12.5, 15.625, 20],
            [5.625, 6.25, 8.125, 11.25, 15.625],
            [2.5, 3.125, 5.0, 8.125, 12.5],
            [0.625, 1.25, 3.125, 6.25, 10.625],
            [0, 0.625, 2.5, 5.625, 10],
        ]
    )
)


server = get_server(client_type="vue2")

with DivLayout(server) as layout:
    plotly.Figure(fig)
    plotly.Figure(fig)

if __name__ == "__main__":
    server.start()
```

<img src="https://github.com/Kitware/trame-plotly/assets/22714778/24191f03-0a24-41d0-a285-115e8d4129a5" width="49%"/>
<img src="https://github.com/Kitware/trame-plotly/assets/22714778/48172be8-4cc7-4122-b353-e38754662cfc" width="49%"/>

I see that it comes from [`vue-components/src/components/TramePlotly.js`](https://github.com/Kitware/trame-plotly/blob/master/vue-components/src/components/TramePlotly.js)
```js
template: `<div style="position: relative; width: 100%; height: 100%;" v-bind="$attrs">
              <div ref="elem" style="position: absolute; width: 100%; height: 100%;"></div>
           </div>`,
```

Is there a way to manage this option? Or should I use it in a better way?

**Comment by jourdain** [comment]
The issue is that the figure use the space available from their parent container (not from the chart). And in your case, they both use the same which has a height of 0px which make them on top of each other.  

if you were to do the following, you should be able to do what you want

```python
with DivLayout(server) as layout:
    with html.Div(style="height: 300px;"):
        plotly.Figure(fig)
   with html.Div(style="height: 300px;"):
        plotly.Figure(fig)
```

The intent of the current setup is to focus on the layout of the UI rather than the size of the chart. With the goal being that the chart should resize to match the available space or at least fill the space you assigned to it and not the other way around.
With that in mind, it is easier to plan and define a layout for your UI. 

Hope that make sense,

Seb

**Comment by kmarchais** [comment]
Works perfectly, thank you very much!
